apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod8182
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod8182
  template:
    metadata:
      labels:
        app: pod8182
    spec:
      containers:
        - name: go-app
          image: ghcr.io/clerikc/3pod8182:latest  
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: pod8182-service
spec:
  selector:
    app: pod8182
  ports:
    - protocol: TCP
      port: 8182      # Внутренний порт сервиса (ClusterIP)
      targetPort: 8080 # Порт контейнера (из Deployment)
      nodePort: 30080  # Порт для доступа снаружи (NodePort, диапазон 30000-32767)
  type: NodePort